"""initial migration

Revision ID: 11e02c8609f3
Revises: 
Create Date: 2025-06-04 21:40:34.311183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '11e02c8609f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('createseller',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('store_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('store_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('store_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('insta_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('invoicecreate',
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['createseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoicecreate_seller_id'), 'invoicecreate', ['seller_id'], unique=False)
    op.create_table('product',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('seller_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['createseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index(op.f('ix_product_seller_id'), 'product', ['seller_id'], unique=False)
    op.create_table('invoiceitems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoicecreate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoiceitems_invoice_id'), 'invoiceitems', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoiceitems_invoice_id'), table_name='invoiceitems')
    op.drop_table('invoiceitems')
    op.drop_index(op.f('ix_product_seller_id'), table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_invoicecreate_seller_id'), table_name='invoicecreate')
    op.drop_table('invoicecreate')
    op.drop_table('createseller')
    # ### end Alembic commands ###
